### ISSUE TITLE
UI crash when trying to show VM instances

### ISSUE THREAD

**Issue by recumbentbirder** [zabbly/incus-ui-canonical#17]
# Description

When trying to show details of _VM_ instances, I get the following error. Switching to another section in the UI menu and reloading revives the UI. This happens with at least different VM instances (tried Arch and Ubuntu), but not with container instances.

# Metadata

UI Version: 0.14
Path: /ui/project/default/instance/third

Installed on Arch Linux, package incus-ui-canonical.

# Stacktrace

```
TypeError: Cannot convert undefined or null to object
    at Function.hasOwn (<anonymous>)
    at r (https://localhost:8443/ui/assets/InstanceDetail-UYmIpX2S.js:1:6156)
    at https://localhost:8443/ui/assets/InstanceDetail-UYmIpX2S.js:1:6185
    at Ya (https://localhost:8443/ui/assets/InstanceDetail-UYmIpX2S.js:1:6209)
    at K_ (https://localhost:8443/ui/assets/index-NBRNnaPi.js:39:17000)
    at yg (https://localhost:8443/ui/assets/index-NBRNnaPi.js:41:3139)
    at jj (https://localhost:8443/ui/assets/index-NBRNnaPi.js:41:44804)
    at Pj (https://localhost:8443/ui/assets/index-NBRNnaPi.js:41:39766)
    at JM (https://localhost:8443/ui/assets/index-NBRNnaPi.js:41:39694)
    at vf (https://localhost:8443/ui/assets/index-NBRNnaPi.js:41:39547)
```

**Comment by recumbentbirder** [comment]
Sorry. That was a duplicate of TWO others before. ... that might be the downside of linking GitHub issues directly in the error message itself ;-)
