### ISSUE TITLE
[Containers] Cannot read properties of undefined (reading 'total')

### ISSUE THREAD

**Issue by thetredev** [zabbly/incus-ui-canonical#22]
# Required information

 * Distribution: Debian
 * Distribution version: 13 / Trixie
 * The output of "incus info" or if that fails:
   * Kernel version: `Linux incus 6.12.6-zabbly+ #debian12 SMP PREEMPT_DYNAMIC Fri Dec 20 21:29:50 UTC 2024 x86_64 GNU/Linux`
   * LXC version: **not sure how to get this one?**
   * Incus version: 6.8
   * Storage backend in use: `dir`

Note: This incus host is bare metal machine running incus directly.

# Issue description

The `incus-ui-canonical` package I have installed is:
```
# apt list --installed | grep incus-ui
incus-ui-canonical/now 1:6.8-ubuntu24.04-202412130713 amd64 [installed,local]
```

Using the UI and clicking on a VM instance works just fine. But clicking on a Container instance causes this error message:
```
Error: Cannot read properties of undefined (reading 'total')
Stack Trace: TypeError: Cannot read properties of undefined (reading 'total')
    at Ha (https://incus.onioncrypto.lan/ui/assets/InstanceDetail-Pl4iR06o.js:1:6897)
    at K_ (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:39:17000)
    at yg (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:3139)
    at jj (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:44804)
    at Pj (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:39766)
    at JM (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:39694)
    at vf (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:39547)
    at xg (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:35914)
    at nS (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:41:36717)
    at qo (https://incus.onioncrypto.lan/ui/assets/index-B893LGfq.js:39:3274)
```

# Steps to reproduce

 1. Install `incus-ui-canonical`
 2. Expose the incus API to some port
 3. Run `incus launch images:debian/trixie my-test-vm` (with or without your custom instance config)
 4. Navigate to the created Container of step 3 using the incus UI

# Information to attach

None of the debug/info logs show anything related to the issue. It seems to be a specific JavaScript thing. Not sure how to debug since the browser doesn't tell me anything about the error either.

Curiously, I have almost the same setup on an my main bare metal machine running Arch Linux with the same version of `incus` and `incus-ui-canonical` (with the latter being installed using the AUR package), which doesn't throw the error mentioned.

# Sooo...

The question I'm having is: am I using the corret UI package? Somehow I believe my Debian Trixie machine doesn't pull `incus-ui-canonical` from the Zabbly repos but I have not idea how to debug/verify/dismiss the theory.

On the Arch machine I am 100% sure it's the correct one, because:
```
$ sudo pacman -Q --info | grep incus-ui
Required By     : incus-ui-canonical
Name            : incus-ui-canonical
URL             : https://github.com/zabbly/incus-ui-canonical
```

**Comment by stgraber** [comment]
@presztak that sounds like it could be related to the disk usage work?

**Comment by presztak** [comment]
@stgraber actually, I took a quick look at the code, and it should not happen anymore for disk object.

@thetredev Can you show the output of: `incus query "/1.0/instances/my-test-vm/state"`?

**Comment by thetredev** [comment]
@presztak here you go:
```
$root@incus:~# incus query "/1.0/instances/sct001/state"
{
	"cpu": {
		"usage": 594250649000
	},
	"disk": {},
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"total": 2147483648,
		"usage": 1314664448,
		"usage_peak": 0
	},
	"network": {
		"br-b12648b93ccb": {
			"addresses": [
				{
					"address": "172.18.0.1",
					"family": "inet",
					"netmask": "16",
					"scope": "global"
				},
				{
					"address": "fe80::42:71ff:fead:c01c",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 4587506,
				"bytes_sent": 81454470,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 2,
				"packets_received": 56471,
				"packets_sent": 56221
			},
			"host_name": "",
			"hwaddr": "02:42:71:ad:c0:1c",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"docker0": {
			"addresses": [
				{
					"address": "172.17.0.1",
					"family": "inet",
					"netmask": "16",
					"scope": "global"
				}
			],
			"counters": {
				"bytes_received": 0,
				"bytes_sent": 0,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 2,
				"packets_received": 0,
				"packets_sent": 0
			},
			"host_name": "",
			"hwaddr": "02:42:7b:48:5c:30",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"eth0": {
			"addresses": [
				{
					"address": "10.0.1.2",
					"family": "inet",
					"netmask": "16",
					"scope": "global"
				},
				{
					"address": "fe80::216:3eff:feb3:e986",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 82982195,
				"bytes_sent": 6617415,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 66718,
				"packets_sent": 66479
			},
			"host_name": "vetha630c896",
			"hwaddr": "00:16:3e:b3:e9:86",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"lo": {
			"addresses": [
				{
					"address": "127.0.0.1",
					"family": "inet",
					"netmask": "8",
					"scope": "local"
				},
				{
					"address": "::1",
					"family": "inet6",
					"netmask": "128",
					"scope": "local"
				}
			],
			"counters": {
				"bytes_received": 48003,
				"bytes_sent": 48003,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 604,
				"packets_sent": 604
			},
			"host_name": "",
			"hwaddr": "",
			"mtu": 65536,
			"state": "up",
			"type": "loopback"
		},
		"veth3191e68": {
			"addresses": [
				{
					"address": "fe80::6442:97ff:fe66:ff07",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 0,
				"bytes_sent": 6396,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 0,
				"packets_sent": 71
			},
			"host_name": "tap1789c755",
			"hwaddr": "66:42:97:66:ff:07",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"veth3e66790": {
			"addresses": [
				{
					"address": "fe80::dc6f:4eff:fea4:c894",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 449472,
				"bytes_sent": 846648,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 2981,
				"packets_sent": 2683
			},
			"host_name": "dmz0",
			"hwaddr": "de:6f:4e:a4:c8:94",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"veth7c132d3": {
			"addresses": [
				{
					"address": "fe80::e421:15ff:fe9b:b0b2",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 4931122,
				"bytes_sent": 80620508,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 53525,
				"packets_sent": 53689
			},
			"host_name": "tap65791775",
			"hwaddr": "e6:21:15:9b:b0:b2",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"vethc7a5a7c": {
			"addresses": [
				{
					"address": "fe80::9cb1:d5ff:fed2:ab6f",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 0,
				"bytes_sent": 6788,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 0,
				"packets_sent": 76
			},
			"host_name": "lan0",
			"hwaddr": "9e:b1:d5:d2:ab:6f",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"vethcd45996": {
			"addresses": [
				{
					"address": "fe80::c8a:6bff:fe2e:3987",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 0,
				"bytes_sent": 6396,
				"errors_received": 0,
				"errors_sent": 0,
				"packets_dropped_inbound": 0,
				"packets_dropped_outbound": 0,
				"packets_received": 0,
				"packets_sent": 71
			},
			"host_name": "veth459038a0",
			"hwaddr": "0e:8a:6b:2e:39:87",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		}
	},
	"os_info": null,
	"pid": 1735,
	"processes": 218,
	"started_at": "2024-12-26T01:24:20.573340396+01:00",
	"status": "Running",
	"status_code": 103
}
```
`sct001` is one such "problematic" container.

**Comment by stgraber** [comment]
Your report shows you're running `202412130713`, the fix for this should have been pushed to `20241219`, can you update your packages and see if that solves it?

**Comment by thetredev** [comment]
Ah, that makes sense. I won't be able to check before around January 2nd because that specific host is down for unrelated reasons at the moment. I'll report back as soon as I can.
