### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by teslaeco** [zabbly/incus-ui-canonical#24]
Generał problem is page 
after some time the page does not respond to opening tabs on the page as if the interface was hanging, and as for the error below, I don't know what it is about, I want to install Linux on this platform so that I can use blender on an Android phone ,
# Description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Metadata

UI Version: 0.14
Path: /ui/project/E=mc%E2%81%B6/instances

# Stacktrace

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gj (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:26089)
    at $r (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27379)
    at yj (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27642)
    at $r (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27529)
    at yj (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27839)
    at $r (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27529)
    at yj (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27642)
    at $r (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27529)
    at yj (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:30579)
    at $r (https://6974ebe5-a98f-4767-8e6c-a35071ba732e.incus-demo.linuxcontainers.org/ui/assets/index-BWo7GFyQ.js:41:27529)
```

**Comment by stgraber** [comment]
After how much time approximately? The online demo only operates for 30min per session, so I'd expect things to break after that 30min expires.
